version: '3.9'

services:
  public:
    build: .
    image: tsicon-public
    command: sh -c "npx prisma db push && npm run start:public"
    ports:
      - "3000:3000"
    environment:
      - IMG_WEB_PORT=3000
      - DATABASE_URL=file:/data/dev.db
    volumes:
      - db-data:/app/dev.db

  local:
    build: .
    image: tsicon-local
    command: sh -c "npx prisma db push && npm run start:local"
    ports:
      - "3001:3001"
    environment:
      - IMG_API_PORT=3001
      - DATABASE_URL=file:/data/dev.db
    volumes:
      - db-data:/app/dev.db

volumes:
  db-data: